{% set name = "importlib-metadata" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 77a540690e24b0305878c37ffd421785a6f7e53c8b5720d211b211de8d0e95da

build:
  number: 0
  skip: true   # [py<=34]
  script: 
    - {{ PYTHON }} -m pip install . -vv       # [py>34]
    - echo "dummy package for python >= 3.8"  # [py>=38]

requirements:
  host:
    - pip
    - python
    - setuptools_scm
  run:
    - configparser >=3.5
    - contextlib2
    - pathlib2
    - python
    - zipp >=0.5

test:
  imports:
    - importlib_metadata
    - importlib_metadata.docs
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://importlib-metadata.readthedocs.io/
  summary: Read metadata from Python packages
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
